### ISSUE TITLE
Discharges from the server 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [DuelMonster/MinersAdvantage#11]
#### Issue description:
Throws from the server as soon as you connect to it.
Initially, I broke the block and thought that it would be tightened by a magnet, as it should be. But at this point I just threw it from the server.
Further attempts to go to the server are unsuccessful - just take off.
#### Does this issue occur on a server or single player world?

- [x] Server
- [ ] Client Only

#### Steps to reproduce:
1. 
2. 
3. 

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage: **MinersAdvantage_1.12.2_1.3.15.198**
- Forge: **spongeforge-1.12.2-2705-7.1.0-BETA-3247**
- Minecraft: **1.12.2**

#### Crash log:

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
**

> **Record from the server log.**

**
[22:47:32] [Netty Server IO #2/ERROR] [minersadvantage]: java.lang.IllegalStateException Exception: 
	at co.uk.duelmonster.minersadvantage.common.Functions.getNearbyEntities(Functions.java:137)
	at co.uk.duelmonster.minersadvantage.handlers.CaptivationHandler.processServerMessage(CaptivationHandler.java:33)
	at co.uk.duelmonster.minersadvantage.packets.NetworkPacket$ServerHandler.onMessage(NetworkPacket.java:169)
	at co.uk.duelmonster.minersadvantage.packets.NetworkPacket$ServerHandler.onMessage(NetworkPacket.java:151)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274)
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:99)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleServerSideCustomPacket(NetworkDispatcher.java:453)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:265)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:72)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Unknown Source)


> **Record from the client log.**

[22:47:21] [main/INFO] [grimpack]: {Grim Pack}: Syncing config from server...
[22:47:21] [main/INFO] [grimpack]: {Grim Pack}: Updating manual pages...
[22:47:21] [main/INFO] [net.spellcraftgaming.lib.gui.override.GuiChatRPGHud]: [CHAT] xxx_LEOPARD_xxx присоединился к игре
[22:47:21] [main/INFO] [net.spellcraftgaming.lib.gui.override.GuiChatRPGHud]: [CHAT] Задание создания: Глава "Мудрец (Садху)": не начата. Глава "Алхимик": не начата. Глава "Падший король": не начата.  Нажмите 'M' для большего количества информации или помощи.
[22:47:21] [main/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity
[22:47:21] [main/INFO] [net.spellcraftgaming.lib.gui.override.GuiChatRPGHud]: [CHAT] Mill?naire 6.2.7 запущен. Исследуйте мир. Нажмите 'V' для отображения списка ближайших поселений.
[22:47:21] [main/INFO] [net.spellcraftgaming.lib.gui.override.GuiChatRPGHud]: [CHAT] Бонусный контент активирован.
[22:47:23] [main/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity
[22:47:25] [main/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity
[22:47:28] [main/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity
[22:47:29] [main/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity
[22:47:48] [main/INFO] [STDOUT]: [com.lycanitesmobs.LycanitesMobs:printInfo:353]: [LycanitesMobs] [Info] [] Config elementalmobs-general created successfully.
[22:47:51] [main/INFO] [Hammer Core]: Cleaning 0 textures from VRAM
[22:47:51] [main/INFO] [journeymap]: Mapping halted in C:\Users\Администратор\AppData\Roaming\.minecraft\journeymap\data\mp\Nitro\DIM0
[22:47:51] [main/WARN] [journeymap]: Existing color palette's mods no longer match current loadout.
[22:47:51] [main/INFO] [journeymap]: WAS: AbyssalCraft:1.9.4.10, ArmorPlus:1.11.2-10.8.0.1, Aroma1997Core:${version}, Aroma1997Core|Helper:1.0, AromaBackup:1.0, AromaBackupRecovery:1.0, AutoSapling:1.11.2-1.3.5, Better Achievements:0.4.1.43, Better Mob-AI:1.1.6[1.11.2], BetterFonts:1.7.4, Bloodmoon:1.5.1, Chest Transporter:2.7.13, ChickenChunks:2.3.1.68, CodeChicken Lib:3.0.0.328, Crafting Tweaks:7.1.9, CraftingTable-IV:1.0, Disenchanter:1.6, Dungeons2!:1.0.0, Easier Villager Trading:1.2, EasyBreeding:4.1.0, ElecCore:1.7.431, Enchantment Descriptions:1.0.3, Epic Siege Mod:12.0.158, Exp Seedling Mod:1.2, FoamFix:@VERSION@, Forge Mod Loader:8.0.99.99, Forgelin:1.4.2, Giacomo's Foundry:1.3.12, Grappling hook mod:1.11.2-v10, Grim Pack:4.0.1.20, Hammer Core:1.9.3.9, HoloInventory:2.0.2.143, Improved Backpacks:1.11.2-1.1.2.0, Infernal Mobs:1.7.2, Inventory Tweaks:1.63+dev.92.4367155, Iron Chest:1.11.2-7.0.24.809, IvToolkit:1.3.3, JourneyMap:1.11.2-5.5.0, Just Enough Items:4.5.1.296, Just Enough Resources:0.6.5.9, LLibrary:1.7.7, Loot Bags:2.4.3, Lycanites Arctic Mobs:1.17.1.2 - MC 1.11.2, Lycanites Demon Mobs:1.17.1.2 - MC 1.11.2, Lycanites Desert Mobs:1.17.1.2 - MC 1.11.2, Lycanites Forest Mobs:1.17.1.2 - MC 1.11.2, Lycanites Freshwater Mobs:1.17.1.2 - MC 1.11.2, Lycanites Inferno Mobs:1.17.1.2 - MC 1.11.2, Lycanites Jungle Mobs:1.17.1.2 - MC 1.11.2, Lycanites Mobs:1.17.1.2 - MC 1.11.2, Lycanites Mountain Mobs:1.17.1.2 - MC 1.11.2, Lycanites Plains Mobs:1.17.1.2 - MC 1.11.2, Lycanites Saltwater Mobs:1.17.1.2 - MC 1.11.2, Lycanites Shadow Mobs:1.17.1.2 - MC 1.11.2, Lycanites Swamp Mobs:1.17.1.2 - MC 1.11.2, MCMultiPart:2.0.1, Malisis Switches:1.11.2-4.1.0, MalisisCore:1.11.2-5.2.5, Minecraft Coder Pack:9.19, Minecraft Forge:13.20.1.2588, Minecraft:1.11.2, MinersAdvantage:1.2.15.194, ModUtilsLib:2.2.1, Mouse Tweaks:2.8, Muon:0.2, Natural Absorption:1.2.2, Player Stats 2:14r, RPG-Hud:3.6.6, Redstone Paste:1.7.4, Refined Storage:1.4.16, Ruins Mod:16.5, SanAndreasPs Mod Library:1.3.0, SanAndreasPs Player Model:1.0.2, ShetiPhian-Core:3.4.7, SignEdit:1.11.2-4, Simple Quarry:1.0.3, Sophisticated Wolves:3.9.1, Spartan Shields:1.3, Subaraki's Common Library:1.2.0.1, TamModized:0.9.2, Telepads:1.11.2-1.0.2.1, Teleporting XP:1.1.1.1, The One Probe:1.4.19, TheDragonLib:1.11.2-3.3.0, Tool Belt:1.7.1, TorchArrowsMod:1.9.4-2, ToroHealth Damage Indicators:1.11.2-11, ToroQuest:1.11.2-4.0, Tree Chopper:1.2.2, TrustCircle:1.11.2-r2, Turret Mod Rebirth:4.0.0-beta.3, Uncrafting Table:1.7.5, Up-Sizer:3.1, Wolf Armor and Storage:1.3.2, Wopper:1.11.2-r3, §eCustomized Dungeon Loot:1.0.1
NOW: AbyssalCraft:1.9.4.10, ArmorPlus:1.12.2-11.13.1.41, Aroma1997Core:2.0.0.0.b155, AromaBackup:2.1.1.3.b103, AromaBackuprecovery:2.1.1.3.b103, Better Advancements:0.0.8.50, Better Mob-AI:1.2.1[1.12.2], BetterFonts:1.9.1, Block Drops:1.4.0, Bloodmoon:1.5.3, Chest Transporter:2.8.8, ChickenChunks:2.4.1.71, CodeChicken Lib:3.2.0.345, Crafting Tweaks:8.1.9, Disenchanter:1.6, Easier Villager Trading:1.2, EasyBreeding:5.0.0, Enchantment Descriptions:1.1.8, Epic Siege Mod:13.161, Exp Seedling Mod:1.2.2, FoamFix:0.9.9.1-1.12.2, Forge Mod Loader:8.0.99.99, Giacomo's Foundry:1.3.13, Grappling hook mod:1.12.2-v10, Grim Pack:5.2.12.78, Hammer Core:1.9.9.17, HoloInventory:2.1.1.151, Improvable Skills:3.4.1r, Improved Backpacks:1.12.2-1.3.0.0, Infernal Mobs:1.7.5, Inventory Tweaks:1.63+release.109.220f184, Iron Chest:1.12.2-7.0.44.829, JourneyMap:1.12.2-5.5.2, Just Enough Items:4.11.0.204, Just Enough Resources:0.8.7.41, Loot Bags:2.5.6, Lycanites Arctic Mobs:1.20.3.1 - MC 1.12.2, Lycanites Demon Mobs:1.20.3.1 - MC 1.12.2, Lycanites Desert Mobs:1.20.3.1 - MC 1.12.2, Lycanites Elemental Mobs:1.20.3.1 - MC 1.12.2, Lycanites Forest Mobs:1.20.3.1 - MC 1.12.2, Lycanites Freshwater Mobs:1.20.3.1 - MC 1.12.2, Lycanites Inferno Mobs:1.20.3.1 - MC 1.12.2, Lycanites Jungle Mobs:1.20.3.1 - MC 1.12.2, Lycanites Mobs:1.20.3.1 - MC 1.12.2, Lycanites Mountain Mobs:1.20.3.1 - MC 1.12.2, Lycanites Plains Mobs:1.20.3.1 - MC 1.12.2, Lycanites Saltwater Mobs:1.20.3.1 - MC 1.12.2, Lycanites Shadow Mobs:1.20.3.1 - MC 1.12.2, Lycanites Swamp Mobs:1.20.3.1 - MC 1.12.2, Millenaire:Mill?naire 6.2.7, Minecraft Coder Pack:9.42, Minecraft Forge:14.23.4.2705, Minecraft:1.12.2, MinersAdvantage:1.3.15.197, Mouse Tweaks:2.8, Muon:0.2, RPG-Hud:3.6.6.2, Redstone Paste:1.7.5, Refined Storage:1.5.34, Ruins Mod:17.1, SanAndreasPs Mod Library:1.4.4, SanAndreasPs Player Model:1.1.1, Shadowfacts' Forgelin:1.7.4, SignEdit:1.12.2-4, Simple Generators:1.12.2-2.0.11a, Sophisticated Wolves:3.13.3, Spartan Shields:1.4.1, Subaraki's Common Library:1.2.0.1, Telepads:$version, Teleporting XP:1.1.1.1, TheDragonLib:1.12.2-5.3.0, Tool Belt:1.7.1, TorchArrows:1.12.1-3, ToroHealth Damage Indicators:1.12.2-11, Tree Chopper:1.2.4, Turret Mod Rebirth:4.0.0-beta.3, Uncrafting Table:1.8-beta6, Universal Modifiers:1.12.2-1.0.9a, Unnatural Absorption:1.2.2, Up-Sizer:4.0.1, Valkyrie Lib:1.12.2-2.0.11a, Waila:1.8.26, What Are We Looking At:2.5.257, Wolf Armor and Storage:2.2.3.6, Wopper:1.12-r5, ?eCustomized Dungeon Loot:1.0.1
[22:47:52] [main/INFO] [FML]: Applying holder lookups
[22:47:52] [main/INFO] [FML]: Holder lookups applied
[22:47:53] [main/INFO] [Improvable Skills]: Reset client skill data.
[22:47:56] [main/INFO] [net.minecraft.client.Minecraft]: Stopping!
[22:47:56] [main/INFO] [net.minecraft.client.audio.SoundManager]: SoundSystem shutting down...
[22:47:57] [main/WARN] [net.minecraft.client.audio.SoundManager]: Author: Paul Lamb, www.paulscode.com
```
</details>

**Comment by DuelMonster** [comment]
I should have a fix for this sorted now, and will release once I have a couple of other things done.

**Comment by DuelMonster** [comment]
Released
