### ISSUE TITLE
Client crash when server "B:"Enforce Server side" any set true

### ISSUE THREAD

**Issue by 0xebjc** [DuelMonster/MinersAdvantage#34]
#### Issue description:
Client crash when server "B:"Enforce Server side" any set true

#### What happens:
When any of the server config settings for "B:"Enforce Server side" are set true, then when a client tries to log into the serve the client crashes.

#### What you expected to happen:
Server rules are enforced on client and no crashes

#### Does this issue occur on a server or single player world?

- [X ] Server
- [X] Client Only (when connecting to server)

#### Steps to reproduce:
1.  Set any of the server "B:"Enforce Server side" to true
2. Run the server and client
3. Login to the server with the client... crash.

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage: MinersAdvantage-1.12.2-1.3.19.243
- Forge: forge-1.12.2-14.23.5.2768-universal
- Minecraft: server and client version 1.12.2

#### Crash log:

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
java.lang.NullPointerException: null
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Excavation.bToggleMode(MAConfig_Excavation.java:58) ~[MAConfig_Excavation.class:?]
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Excavation.bToggleMode(MAConfig_Excavation.java:59) ~[MAConfig_Excavation.class:?]
> 	at co.uk.duelmonster.minersadvantage.events.ClientEvents.onClientTick(ClientEvents.java:124) ~[ClientEvents.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1228_ClientEvents_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) ~[FMLCommonHandler.class:?]
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1707) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> [17:07:59] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   ApotheosisCore (Apotheosis-1.12.2-1.9.3.jar)
>   LoadingPlugin (Quark-r1.5-146.jar)
>   Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
>   offlineskins (OfflineSkins-1.12.2-v5g-core.jar)
>   NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
>   RandomPatches (randompatches-1.12.2-1.15.0.2.jar)
>   FCFMLCorePlugin (FinderCompass-1.12.1.jar)
>   Sneaky Curses (SneakyCurses-v1.0-1.12.2.jar)
>   ColytraLoadingPlugin (colytra-1.12.2-1.1.1.jar)
>   ForgelinPlugin (Forgelin-1.8.2.jar)
>   PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.0+build37-universal.jar)
>   SurgeLoadingPlugin (Surge-1.12.2-2.0.76.jar)
>   Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
>   SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
>   IvToolkit (IvToolkit-1.3.3-1.12.jar)
>   DLFMLCorePlugin (DynamicLights-1.12.2.jar)
>   ReBind Core (rebind-1.12.2-2.7.5-0.jar)
>   llibrary (llibrary-core-1.0.8-1.12.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // But it works on my machine.
> 
> Time: 6/9/19 5:07 PM
> Description: Unexpected error
> 
> java.lang.NullPointerException: Unexpected error
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Excavation.bToggleMode(MAConfig_Excavation.java:58)
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Excavation.bToggleMode(MAConfig_Excavation.java:59)
> 	at co.uk.duelmonster.minersadvantage.events.ClientEvents.onClientTick(ClientEvents.java:124)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1228_ClientEvents_onClientTick_ClientTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1707)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Excavation.bToggleMode(MAConfig_Excavation.java:58)
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Excavation.bToggleMode(MAConfig_Excavation.java:59)
> 	at co.uk.duelmonster.minersadvantage.events.ClientEvents.onClientTick(ClientEvents.java:124)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1228_ClientEvents_onClientTick_ClientTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
> 
> -- Affected level --
```
</details>

**Comment by 0xebjc** [comment]
Using forge version 14.23.5.2847 and MinersAdvantage-1.12.2-1.3.19.244 I was able to set the forced server settings and the run the game without crashing.  I'm suspecting this might be from copying the client config to the server?  I noticed that the sever generates a different format for the config, might be part of the cause?

**Comment by 0xebjc** [comment]
Here's a stacktrace of the crash; let me know if you want a full crashlog?

```
java.lang.NullPointerException: null
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Captivation.bEnabled(MAConfig_Captivation.java:32) ~[MAConfig_Captivation.class:?]
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Captivation.bEnabled(MAConfig_Captivation.java:32) ~[MAConfig_Captivation.class:?]
> 	at co.uk.duelmonster.minersadvantage.events.ClientEvents.onClientTick(ClientEvents.java:105) ~[ClientEvents.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1738_ClientEvents_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) ~[FMLCommonHandler.class:?]
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> [12:06:45] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
>   ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.9.jar)
>   CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
>   ForgelinPlugin (Forgelin-1.8.4.jar)
>   Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
>   offlineskins (OfflineSkins-1.12.2-v5g-core.jar)
>   TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
>   NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
>   FCFMLCorePlugin (FinderCompass-1.12.1.jar)
>   ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
>   RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
>   llibrary (llibrary-core-1.0.11-1.12.2.jar)
>   SurgeLoadingPlugin (Surge-1.12.2-2.0.76.jar)
>   BetterSprintingCore (BetterSprinting-1.12.2-v3.0.1.jar)
>   ApotheosisCore (Apotheosis-1.12.2-1.12.4.jar)
>   PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
>   ChunkGenLimiterCoremod (chunkgenlimiter-1.1-core.jar)
>   Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
>   MobsOnRails (MobsOnRails-1.12.2-1.0.0.jar)
>   IvToolkit (IvToolkit-1.3.3-1.12.jar)
>   ReBind Core (rebind-1.12.2-2.7.5-0.jar)
>   TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
>   ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
>   Quark Plugin (Quark-r1.6-178(Tweaked).jar)
> Contact their authors BEFORE contacting forge
> 
> // Shall we play a game?
> 
> Time: 3/21/20 12:06 PM
> Description: Unexpected error
> 
> java.lang.NullPointerException: Unexpected error
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Captivation.bEnabled(MAConfig_Captivation.java:32)
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Captivation.bEnabled(MAConfig_Captivation.java:32)
> 	at co.uk.duelmonster.minersadvantage.events.ClientEvents.onClientTick(ClientEvents.java:105)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1738_ClientEvents_onClientTick_ClientTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Captivation.bEnabled(MAConfig_Captivation.java:32)
> 	at co.uk.duelmonster.minersadvantage.config.MAConfig_Captivation.bEnabled(MAConfig_Captivation.java:32)
> 	at co.uk.duelmonster.minersadvantage.events.ClientEvents.onClientTick(ClientEvents.java:105)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1738_ClientEvents_onClientTick_ClientTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [EntityPlayerSP['Simon'/8179, l='MpServer', x=-219.06, y=81.91, z=177.48]]
> 	Chunk stats: MultiplayerChunkCache: 441, 441
> 	Level seed: 0
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (-184,64,256), Chunk: (at 8,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 2983029 game time, 597930 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Forced entities: 77 total; [EntityChicken['Chicken'/8192, l='MpServer', x=-182.26, y=87.00, z=115.62], EntitySheep['Sheep'/8193, l='MpServer', x=-186.55, y=80.00, z=120.96], EntityItem['item.item.feather'/8194, l='MpServer', x=-182.54, y=87.00, z=115.13], EntityVillager['Star'/133, l='MpServer', x=-217.77, y=68.00, z=161.71], EntityVillager['Nicholas'/134, l='MpServer', x=-218.50, y=68.00, z=161.26], EntityChicken['Chicken'/8326, l='MpServer', x=-216.50, y=78.00, z=108.12], EntityPig['Pig'/135, l='MpServer', x=-220.76, y=66.00, z=252.84], EntitySheep['Sheep'/8327, l='MpServer', x=-217.04, y=79.00, z=97.68], EntitySheep['Sheep'/8328, l='MpServer', x=-222.27, y=79.00, z=102.80], EntityFirefly['Firefly'/905, l='MpServer', x=-224.89, y=71.56, z=149.38], EntityChicken['Chicken'/8329, l='MpServer', x=-221.05, y=79.00, z=98.49], EntitySheep['Lasonya'/143, l='MpServer', x=-195.80, y=67.00, z=223.29], EntitySheep['Sheep'/144, l='MpServer', x=-203.22, y=67.00, z=239.51], EntitySheep['Sheep'/145, l='MpServer', x=-200.22, y=67.00, z=242.58], EntitySheep['Sheep'/8337, l='MpServer', x=-263.24, y=68.00, z=110.47], EntityStray['Stray'/8338, l='MpServer', x=-258.50, y=70.00, z=104.50], EntityChameleon['Chameleon'/8339, l='MpServer', x=-271.24, y=67.00, z=104.48], EntityCreeper['Creeper'/8340, l='MpServer', x=-269.50, y=67.00, z=105.50], EntitySophisticatedWolf['Sophisticated Wolf'/8345, l='MpServer', x=-243.50, y=79.00, z=90.50], EntityCreeper['Creeper'/8860, l='MpServer', x=-292.50, y=63.00, z=121.50], EntityGoblin['Goblin'/8350, l='MpServer', x=-245.50, y=20.00, z=103.50], EntityZombieVillager['Zombie Villager'/8862, l='MpServer', x=-287.50, y=63.00, z=126.50], EntitySkeletonWarrior['Skeleton Warrior'/8351, l='MpServer', x=-255.50, y=59.00, z=99.50], EntitySophisticatedWolf['Sophisticated Wolf'/161, l='MpServer', x=-184.45, y=77.06, z=129.72], EntityBat['Bat'/8612, l='MpServer', x=-215.50, y=19.00, z=166.50], EntityGoblin['Goblin'/10662, l='MpServer', x=-229.50, y=25.00, z=126.50], EntityBat['Bat'/8615, l='MpServer', x=-212.50, y=19.00, z=164.50], EntityWroughtnaut['Ferrous Wroughtnaut'/168, l='MpServer', x=-165.50, y=40.00, z=144.50], EntitySheep['Sheep'/171, l='MpServer', x=-149.81, y=67.00, z=247.50], EntityBat['Bat'/8619, l='MpServer', x=-229.50, y=23.00, z=105.50], EntityBat['Bat'/8620, l='MpServer', x=-233.50, y=23.00, z=102.50], EntitySheep['Sheep'/173, l='MpServer', x=-141.45, y=76.00, z=136.55], EntitySheep['Sheep'/174, l='MpServer', x=-141.44, y=80.00, z=129.75], EntityBat['Bat'/8622, l='MpServer', x=-236.50, y=23.00, z=108.50], EntitySupportCreeper['Support Creeper'/9016, l='MpServer', x=-212.50, y=26.00, z=161.50], EntitySkeletonWarrior['Skeleton Warrior'/8634, l='MpServer', x=-228.50, y=23.00, z=105.50], EntitySkeletonWarrior['Skeleton Warrior'/8635, l='MpServer', x=-225.50, y=23.00, z=104.50], EntitySkeletonWarrior['Skeleton Warrior'/10176, l='MpServer', x=-191.50, y=68.00, z=233.50], EntityCitizen['Haylie K. Gifford'/162, l='MpServer', x=-190.59, y=69.06, z=191.50], EntityGoblin['Goblin'/8257, l='MpServer', x=-153.50, y=40.00, z=105.50], EntityGoblin['Goblin'/8258, l='MpServer', x=-154.50, y=40.00, z=104.50], EntityZombie['Zombie'/8902, l='MpServer', x=-298.50, y=69.00, z=167.50], EntityZombie['Zombie'/8903, l='MpServer', x=-297.50, y=69.00, z=163.50], EntitySkeletonWarrior['Skeleton Warrior'/10956, l='MpServer', x=-202.50, y=35.00, z=183.50], EntityGoblin['Goblin'/10574, l='MpServer', x=-232.50, y=35.00, z=157.50], EntitySheep['Sheep'/8272, l='MpServer', x=-187.49, y=85.00, z=104.76], EntitySupportCreeper['Support Creeper'/9555, l='MpServer', x=-248.50, y=35.00, z=127.50], EntityGoblin['Goblin'/8919, l='MpServer', x=-233.50, y=39.00, z=124.50], EntityBat['Bat'/8800, l='MpServer', x=-216.50, y=37.00, z=155.50], EntityPlayerSP['Simon'/8179, l='MpServer', x=-219.06, y=81.91, z=177.48], EntityGoblin['Goblin'/8931, l='MpServer', x=-164.50, y=37.00, z=128.50], EntityTravelingMerchant['Deloris'/1384, l='MpServer', x=-260.60, y=67.00, z=145.49], EntityButterfly['Butterfly'/8808, l='MpServer', x=-249.50, y=67.00, z=194.50], EntityButterfly['Butterfly'/8809, l='MpServer', x=-246.50, y=67.00, z=193.50], EntityButterfly['Butterfly'/8810, l='MpServer', x=-245.50, y=67.00, z=196.50], EntitySupportCreeper['Support Creeper'/8939, l='MpServer', x=-274.50, y=63.00, z=120.50], EntityCow['Cow'/108, l='MpServer', x=-259.95, y=67.00, z=130.42], EntitySheep['Sheep'/109, l='MpServer', x=-267.82, y=70.00, z=163.74], EntityGoblin['Goblin'/8305, l='MpServer', x=-226.50, y=23.00, z=103.50], EntityGoblin['Goblin'/8306, l='MpServer', x=-226.50, y=23.00, z=106.50], EntitySophisticatedWolf['Sophisticated Wolf'/115, l='MpServer', x=-241.56, y=1.00, z=196.50], EntitySheep['Sheep'/8307, l='MpServer', x=-233.43, y=79.00, z=105.24], EntityFirefly['Firefly'/8180, l='MpServer', x=-276.54, y=69.69, z=115.09], EntityFirefly['Firefly'/1910, l='MpServer', x=-200.06, y=76.89, z=130.05], EntitySkeletonWarrior['Skeleton Warrior'/8182, l='MpServer', x=-260.50, y=13.00, z=115.50], EntityZombie['Zombie'/8183, l='MpServer', x=-243.50, y=23.00, z=113.19], EntitySupportCreeper['Support Creeper'/8184, l='MpServer', x=-255.50, y=21.00, z=118.50], EntityGroveSprite['Grove Sprite'/8185, l='MpServer', x=-240.50, y=71.00, z=119.50], EntityGoblin['Goblin'/9081, l='MpServer', x=-259.50, y=30.00, z=131.50], EntityZombie['Zombie'/8186, l='MpServer', x=-228.50, y=20.00, z=119.50], EntityGoblin['Goblin'/9082, l='MpServer', x=-259.50, y=30.00, z=133.50], EntitySheep['Sheep'/8187, l='MpServer', x=-222.77, y=75.00, z=117.52], EntitySheep['Sheep'/8188, l='MpServer', x=-197.45, y=79.00, z=116.82], EntityChicken['Chicken'/8189, l='MpServer', x=-182.20, y=87.00, z=115.20], EntitySheep['Sheep'/8190, l='MpServer', x=-182.26, y=82.00, z=118.80], EntityCreeper['Creeper'/8958, l='MpServer', x=-143.50, y=66.00, z=223.50], EntityChicken['Chicken'/8191, l='MpServer', x=-183.84, y=86.00, z=115.49]]
> 	Retry entities: 0 total; []
> 	Server brand: fml,forge
> 	Server type: Non-integrated multiplayer server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by 0xebjc** [comment]
Tested, crashes if the server has config 
```
"Override Client Feature Enablement§r"=true
```
on both cases if client has same setting true or false
