### ISSUE TITLE
Game close when switching to Survival

### ISSUE THREAD

**Issue by ZomecGaming** [DuelMonster/MinersAdvantage#35]
The world will not start if the character is in survival mode. The world will close if you switch to survival mode. It will produce the following error.

NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28)
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DuelMonster** [comment]
Thank you for reporting this issue; however, nothing in that error points to MinersAdvantage.

In order to look into this further the full error log and version info would be more helpful.
This is why a new issue template was provided to assist you in providing enough detail:

<details><summary>New Issue Template</summary>

```
<!-- Be as accurate as possible. Add/remove as needed to keep things informative but also relevant. -->
#### Issue description:

#### What happens:

#### What you expected to happen:

#### Does this issue occur on a server or single player world?
<!-- Replace the space ' ' with an 'x' in the relevant box. -->
- [ ] Server
- [ ] Client Only

#### Steps to reproduce:
1. 
2. 
3. 

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage:
- Forge:
- Minecraft:

#### Crash log:
<!-- Paste relevent crash log below ( if relevant ) -->

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

PASTE_HERE

</details>

```
</details>
