### ISSUE TITLE
Mod incompatible with Optifine 1.16.2

### ISSUE THREAD

**Issue by poots6** [DuelMonster/MinersAdvantage#55]
#### Issue description:
Incompatible with Optifine 1.16.2 and crashes because of the new GUI inclusion (theory).

#### What happens:
Game crashes.

#### What you expected to happen:
Game to load normally.

#### Does this issue occur on a server or single player world?

- [ ] Server
- [x] Client Only

#### Steps to reproduce:
1. Install Forge, MinersAdvantage, Optifine, and Erdbeerbaer's GUI Library for 1.16.
2. Run game

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage: 1.16.2-1.6.3.151
- Forge: 33.0.61
- Minecraft: 1.16.2
- Optifine: 1.16.2 HD U G3
- Erdbeerbaer's GUI Library: 1.0.3-1.16

#### Crash log:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 9/28/20 9:14 PM
Description: Rendering overlay

java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
	at net.optifine.util.TextureUtils.getImageSize(TextureUtils.java:669)
	at net.minecraft.client.renderer.texture.AtlasTexture.detectMinimumSpriteSize(AtlasTexture.java:817)
	at net.minecraft.client.renderer.texture.AtlasTexture.detectMaxMipmapLevel(AtlasTexture.java:780)
	at net.minecraft.client.renderer.texture.AtlasTexture.func_229220_a_(AtlasTexture.java:276)
	at net.minecraft.client.renderer.model.ModelBakery.processLoading(ModelBakery.java:257)
	at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:72)
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:57)
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:20)
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11)
	at net.minecraft.client.resources.ReloadListener$$Lambda$3529/1629292387.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.util.TextureUtils.getImageSize(TextureUtils.java:669)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.61.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/703627308.call(Unknown Source) [forge-1.16.2-33.0.61.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7288235744 bytes (6950 MB) / 10334765056 bytes (9856 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.61.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.61.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.61.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.61.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.2_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.61.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.61
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.61-client.jar Minecraft {minecraft@1.16.2 PROCESS_IMC}
		randomblockplacement-1.16.2-forge33.0.5-1.0.jar RandomBlockPlacement {randomblockplacement@1.16.2-forge33.0.5-1.0 PROCESS_IMC}
		eguilib-1.0.3-1.16.jar Erdbeerbaer's GUI Library {eguilib@1.0.3 PROCESS_IMC}
		forge-1.16.2-33.0.61-universal.jar Forge {forge@33.0.61 ERROR}
		worldedit-forge-mc1.16.2-7.2.0-beta-04.jar WorldEdit {worldedit@7.2.0-beta-04+98f71a3 PROCESS_IMC}
		MinersAdvantage-1.16.2-1.6.3.151.jar MinersAdvantage {minersadvantage@1.16.2-1.6.3.151 PROCESS_IMC}
	Launched Version: 1.16.2-forge-33.0.61
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.16.2_HD_U_G3
	OptiFine Build: 20200829-104659
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 452.06
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by poots6** [comment]
Same issue with 1.16.3.

Forge: 34.1.0
Erdbeerbaer's GUI Library: 1.0.3-1.16
MinersAdvantage: 1.16.3-1.7.3.153
Optifine: 1.16.3 HD U G3
