### ISSUE TITLE
Crash during cropination use - hoe durability

### ISSUE THREAD

**Issue by Plus9000** [DuelMonster/MinersAdvantage#69]
#### Does this issue occur on a server or single player world?

- [ ] Server
- [x] Client Only

#### Steps to reproduce:
1. Get a hoe to extremely low durability
2. use cropination auto-harvest on crops

#### Versions (make sure you are on the latest version before reporting): 

- MinersAdvantage:1.9.1.180
- Forge: 36.0.58
- Minecraft:1.16.5

#### Crash log:

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
[28Mar2021 19:42:33.638] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: net.minecraftforge.common.ForgeInternalHandler@79bdcf61 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		2: ASM: uk.co.duelmonster.minersadvantage.events.server.ServerEventHandler@77dd9f05 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_222118_a(ItemStack.java:306)
	at uk.co.duelmonster.minersadvantage.workers.CropinationAgent.tick(CropinationAgent.java:117)
	at uk.co.duelmonster.minersadvantage.workers.AgentProcessor.fireAgentTicks(AgentProcessor.java:60)
	at uk.co.duelmonster.minersadvantage.events.server.ServerEventHandler.onServerTick(ServerEventHandler.java:102)
	at net.minecraftforge.eventbus.ASMEventHandler_42_ServerEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2595/724620742.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$5422/1866841711.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[28Mar2021 19:42:33.639] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.item.ItemStack.func_222118_a(ItemStack.java:306) ~[?:?]
	at uk.co.duelmonster.minersadvantage.workers.CropinationAgent.tick(CropinationAgent.java:117) ~[?:1.16.5-1.9.1.180]
	at uk.co.duelmonster.minersadvantage.workers.AgentProcessor.fireAgentTicks(AgentProcessor.java:60) ~[?:1.16.5-1.9.1.180]
	at uk.co.duelmonster.minersadvantage.events.server.ServerEventHandler.onServerTick(ServerEventHandler.java:102) ~[?:1.16.5-1.9.1.180]
	at net.minecraftforge.eventbus.ASMEventHandler_42_ServerEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2595/724620742.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5422/1866841711.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[28Mar2021 19:42:33.645] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID a7c432b6-d1bb-40ba-84d0-61818274be25
```
</details>

**Comment by rwilkin** [comment]
This also happens if you don't have a hoe in your inventory
