### ISSUE TITLE
minecart crashes game

### ISSUE THREAD

**Issue by Hessin87** [DuelMonster/MinersAdvantage#71]
#### Issue description:
	Game crashes when attempting to break a minecart with substitution toggled on

#### What happens:
	Game crashes when attempting to break a minecart with substitution toggled on

#### What you expected to happen:
	switch to my pickaxe and break the minecart with it

#### Does this issue occur on a server or single player world?

- [ ] Server
- [x] Client Only... I think? chunks are saved before the game crashes im in survival single player "SSP" if that helps

#### Steps to reproduce:
1. place minecart, doesn't matter if it has a hopper or chest or nothing in it. haven't tested with pistons or furnaces
2. forget to switch off "substitution"
3. left click on minecart
4. game crashes
5. I just realized I have a mod called "moreminecarts-1.3.8", I'll submit this anyway because I'm pretty sure that mod only adds rails and doesn't change the minecart, but I'll update the issue in a few minutes to let you know if uninstalling moreminecarts fixes it

#### Versions (make sure you are on the latest version before reporting):

- MinersAdvantage:	-1.16.5-1.9.1.180
- Forge:		-1.16.5-36.2.0
- Minecraft:		-1.16.5

#### Crash log:

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/25/21 2:32 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.entity.item.minecart.MinecartEntity cannot be cast to net.minecraft.entity.LivingEntity
	at uk.co.duelmonster.minersadvantage.helpers.SubstitutionHelper.processWeaponSubtitution(SubstitutionHelper.java:230) ~[?:1.16.5-1.9.1.180] {re:classloading}
	at uk.co.duelmonster.minersadvantage.events.client.ClientEventHandler.onAttackEntity(ClientEventHandler.java:123) ~[?:1.16.5-1.9.1.180] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_443_ClientEventHandler_onAttackEntity_AttackEntityEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2593/1527072432.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:766) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1044) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing}
	at net.minecraft.client.multiplayer.PlayerController.func_78764_a(PlayerController.java:352) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:fantasy.mixins.json:PlayerControllerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1305) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/230991505.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at uk.co.duelmonster.minersadvantage.helpers.SubstitutionHelper.processWeaponSubtitution(SubstitutionHelper.java:230) ~[?:1.16.5-1.9.1.180] {re:classloading}
	at uk.co.duelmonster.minersadvantage.events.client.ClientEventHandler.onAttackEntity(ClientEventHandler.java:123) ~[?:1.16.5-1.9.1.180] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_443_ClientEventHandler_onAttackEntity_AttackEntityEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2593/1527072432.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:766) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1044) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing}
	at net.minecraft.client.multiplayer.PlayerController.func_78764_a(PlayerController.java:352) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:fantasy.mixins.json:PlayerControllerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1305) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Hessin87'/273, l='ClientLevel', x=-19.19, y=1.00, z=-7.21]]
	Chunk stats: Client Chunk Cache: 2809, 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,63,135), Chunk: (at 0,3,7 in -5,8; contains blocks -80,0,128 to -65,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3387472 game time, 1810900 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/230991505.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5246414080 bytes (5003 MB) / 7314866176 bytes (6976 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		CyclopsCore-1.16.5.jar                            |Cyclops Core                  |cyclopscore                   |1.11.7              |DONE      |Manifest: NOSIGNATURE
		physics-mod-1.3.4_forge.jar                       |Physics Mod                   |physicsmod                    |1.0                 |DONE      |Manifest: NOSIGNATURE
		teleportmod_1.16.3-1.1.3.jar                      |Teleport++                    |teleportmod                   |1.1.3               |DONE      |Manifest: NOSIGNATURE
		flatbedrock-1.16.4-1.1.6.jar                      |Flat Bedrock                  |flatbedrock                   |1.16.4-1.1.6        |DONE      |Manifest: NOSIGNATURE
		cavebiomes-2.0.jar                                |CaveBiomeAPI                  |cavebiomes                    |2.0                 |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |DONE      |Manifest: NOSIGNATURE
		chunksavingfix-0.1.0.jar                          |Chunk Saving Fix              |chunksavingfix                |0.1.0               |DONE      |Manifest: NOSIGNATURE
		EverlastingAbilities-1.16.5-1.7.1.jar             |EverlastingAbilities          |everlastingabilities          |1.7.1               |DONE      |Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |Manifest: NOSIGNATURE
		CavesAndCliffsBackport-6.1.jar                    |Caves & Cliffs Backport       |cavesandcliffs                |6.1                 |DONE      |Manifest: NOSIGNATURE
		ProjectE-1.16.5-PE1.0.1B.jar                      |ProjectE                      |projecte                      |PE1.0.1B            |DONE      |Manifest: NOSIGNATURE
		randomenchants-4.0.8.jar                          |Random Enchants               |randomenchants                |4.0.8               |DONE      |Manifest: NOSIGNATURE
		Inventory-Tweaks-Renewed-Mod-1.16.5.jar           |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		hole_filler_mod-1.2.4.2-mc_1.16.x-forge.jar       |Hole Filler Mod               |hole_filler_mod               |1.2.4.2             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.14.0_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |21.14.0             |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |DONE      |Manifest: NOSIGNATURE
		BetterPortals-1.16.4-0.3.6.jar                    |YUNG's Better Portals         |betterportals                 |1.16.4-0.3.6        |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.6.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.6        |DONE      |Manifest: NOSIGNATURE
		Clumps-Mod-1.16.5.jar                             |Clumps                        |clumps                        |6.0.0.25            |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.15.0.1_Forge_1.16.5.jar          |Xaero's World Map             |xaeroworldmap                 |1.15.0.1            |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.120-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.119    |DONE      |Manifest: NOSIGNATURE
		configured-1.1.0-1.16.5.jar                       |Configured                    |configured                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-11.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-11     |DONE      |Manifest: NOSIGNATURE
		moreminecarts-1.3.8.jar                           |More Minecarts                |moreminecarts                 |1.3.8               |DONE      |Manifest: NOSIGNATURE
		GunpowderLib-1.16.5-1.2.2.jar                     |GunpowderLib                  |gunpowderlib                  |1.16.5-1.2.2        |DONE      |Manifest: 2e:cb:db:61:22:2a:6d:79:f4:22:31:8c:34:9b:cf:9f:91:ea:95:c4:bf:bb:8a:de:6e:10:c3:f0:b1:c6:ae:20
		SimpleSponge-1.16.5-5.0.1.jar                     |Simple Sponge                 |simplesponge                  |5.0.1               |DONE      |Manifest: 2e:cb:db:61:22:2a:6d:79:f4:22:31:8c:34:9b:cf:9f:91:ea:95:c4:bf:bb:8a:de:6e:10:c3:f0:b1:c6:ae:20
		fantasy-forge-1.1.1.jar                           |Fantasy Mounts                |fantasy                       |1.0                 |DONE      |Manifest: NOSIGNATURE
		Uncrafted-Mod-1.16.3.jar                          |Uncrafted                     |uncrafted                     |4.0.0pre1           |DONE      |Manifest: NOSIGNATURE
		infinitemusic-1.3.0.jar                           |Infinite Music                |infinitemusic                 |1.3.0               |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |Manifest: NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		Actually.Useful.Smithing.Table-1.0.2.mc.1.16.3.jar|Actually Useful Smithing Table|actuallyusefulsmithingtable   |1.0.2 mc 1.16.3     |DONE      |Manifest: NOSIGNATURE
		architectury-1.20.28-forge.jar                    |Architectury                  |architectury                  |1.20.28             |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.1-build.48.jar           |FTB Library                   |ftblibrary                    |1605.3.1-build.48   |DONE      |Manifest: NOSIGNATURE
		hplus-forge-2.0.0.jar                             |HopperPlus                    |hplus                         |NONE                |DONE      |Manifest: NOSIGNATURE
		weirdinggadget-1.16.(2-4)-2.2.7.jar               |The Weirding Gadget           |weirdinggadget                |2.2.7               |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		catalogue-1.2.1-1.16.5.jar                        |Catalogue                     |catalogue                     |1.2.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |DONE      |Manifest: NOSIGNATURE
		Paraglider-1.16.5-1.3.1.1.jar                     |Paraglider                    |paraglider                    |1.3.1.1             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		exnihilosequentia-1.16-20210628182320.jar         |Ex Nihilo: Sequentia          |exnihilosequentia             |1.16-20210628182320 |DONE      |Manifest: NOSIGNATURE
		CustomStartingGear-1.16.4-2.0.2.1-universal.jar   |Custom Starter Gear           |customstartinggear            |2.0.2.1             |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta21.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta21|DONE      |Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar          |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta10 |DONE      |Manifest: NOSIGNATURE
		MinersAdvantage-1.16.5-1.9.1.180.jar              |MinersAdvantage               |minersadvantage               |1.16.5-1.9.1.180    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2edbc58f-3e86-4a05-a0f5-1faac371fe45
	Launched Version: 1.16.5-forge-36.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX TITAN/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.41, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 8x Intel(R) Xeon(R) CPU E31240 @ 3.30GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 24
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.0.01.zip
	OpenGlVersion: 4.6.0 NVIDIA 471.41
	OpenGlRenderer: NVIDIA GeForce GTX TITAN/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```
</details>

**Comment by Hessin87** [comment]
uninstalling moreminecarts did not fix the issue
