### ISSUE TITLE
The Problem in Harvesting

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [DuelMonster/MinersAdvantage#9]
**Hello!
I had a problem with the server. The thing is that when I try to harvest, my server crashes.
Version 1.11.2**

#### Crash log:

<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
WARNING: coremods are present:
  MalisisCorePlugin (malisiscore_1.11.2-5.2.5.jar)
  SpongeCoremod (spongeforge-1.11.2-2476-6.1.0-BETA-2792.jar)
  CoreMod (Aroma1997Core_1.11.2_1.2.0.0.jar)
  ImprovedMobs/ASM (ImprovedMobs_1.1.61.11.2.jar)
  MalisisSwitchesPlugin (malisisswitches_1.11.2-4.1.0.jar)
  ForgelinPlugin (Forgelin_1.4.2.jar)
  llibrary (llibrary_1.7.7_1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore_1.11.0_3.4.7.jar)
  IvToolkit (IvToolkit_1.3.3._1.11.2jar.jar)
  HammerCoreCore (HammerCore_1.11.2-1.9.3.9.jar)
  NWRTweak (redstonepaste_mc1.11.2_1.7.4.jar)
  LoadingPlugin (Bloodmoon_MC1.11.x_1.5.1.jar)
  MuonPlugin (muon_0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks_1.11.2_1.63dev.92.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 24.06.18 11:33
Description: Exception in server tick loop

java.lang.ClassCastException: java.util.ArrayList cannot be cast to net.minecraft.util.NonNullList
	at co.uk.duelmonster.minersadvantage.workers.CropinationAgent.tick(CropinationAgent.java:113)
	at co.uk.duelmonster.minersadvantage.workers.AgentProcessor.fireAgentTicks(AgentProcessor.java:58)
	at co.uk.duelmonster.minersadvantage.events.ServerEvents.onServerTick(ServerEvents.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_272_ServerEvents_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at co.uk.duelmonster.minersadvantage.workers.CropinationAgent.tick(CropinationAgent.java:113)
	at co.uk.duelmonster.minersadvantage.workers.AgentProcessor.fireAgentTicks(AgentProcessor.java:58)
	at co.uk.duelmonster.minersadvantage.events.ServerEvents.onServerTick(ServerEvents.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_272_ServerEvents_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632)

-- Sponge CauseTracker --
Details:
	Cause Stack: /********************************************************************************************************/
/*   - Phase: org.spongepowered.common.event.tracking.phase.plugin.PostServerTickListenerState@5c82c36a */
/*     Context:                                                                                         */
/*     - Name: Source                                                                                   */
/*       Object: ASM: co.uk.duelmonster.minersadvantage.events.ServerEvents@653f7e8b                    */
/*       onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V             */
/*     - Name: CapturedWorldTickEvent                                                                   */
/*       Object: net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@1510ad03             */
/*     - Name: CapturedBlocks                                                                           */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                     */
/*     - Name: CapturedEntities                                                                         */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                   */
/*     - Name: CapturedPlayer                                                                           */
/*       Object: CapturePlayer{player=null}                                                             */
/********************************************************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zhl000(MinecraftServer.java:3974)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:840)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:358)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:514)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 317099792 bytes (302 MB) / 1061486592 bytes (1012 MB) up to 10650189824 bytes (10156 MB)
	JVM Flags: 2 total; -Xincgc -Xmx10G
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2588 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2588-universal.jar) 
	UCHIJAAAA	forge{13.20.1.2588} [Minecraft Forge] (forge-1.11.2-13.20.1.2588-universal.jar) 
	UCHIJAAAA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core_1.11.2_1.2.0.0.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	muon{0.2} [Muon] (minecraft.jar) 
	UCHIJAAAA	spongeapi{6.1.0-SNAPSHOT-d1eb7e2} [SpongeAPI] (spongeforge-1.11.2-2476-6.1.0-BETA-2792.jar) 
	UCHIJAAAA	sponge{1.11.2-2476-6.1.0-BETA-2792} [SpongeForge] (spongeforge-1.11.2-2476-6.1.0-BETA-2792.jar) 
	UCHIJAAAA	jei{4.5.1.296} [Just Enough Items] (jei_1.11.2_4.5.1.296.jar) 
	UCHIJAAAA	abyssalcraft{1.9.4.10} [AbyssalCraft] (AbyssalCraft_1.11.2_1.9.4.10.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Forgelin] (Forgelin_1.4.2.jar) 
	UCHIJAAAA	thedragonlib{1.11.2-3.3.0} [TheDragonLib] (thedragonlib_1.11.2-3.3.0.jar) 
	UCHIJAAAA	armorplus{1.11.2-10.8.0.1} [ArmorPlus] (armorplus_1.11.2-10.8.0.1.jar) 
	UCHIJAAAA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core_1.11.2_1.2.0.0.jar) 
	UCHIJAAAA	aromabackup{1.0} [AromaBackup] (AromaBackup_1.11_2.1.0.0.jar) 
	UCHIJAAAA	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup_1.11_2.1.0.0.jar) 
	UCHIJAAAA	autosapling{1.11.2-1.3.5} [AutoSapling] (AutoSapling_1.11.2_1.3.5.jar) 
	UCHIJAAAA	betterachievements{0.4.1.43} [Better Achievements] (BetterAchievements_1.11.2_0.4.1.43.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands_1.11_0.11.1.2399162f74.jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon_MC1.11.x_1.5.1.jar) 
	UCHIJAAAA	chesttransporter{2.7.13} [Chest Transporter] (ChestTransporter_1.11.2_2.7.13.jar) 
	UCHIJAAAA	eleccore{1.7.431} [ElecCore] (ElecCore_1.11-1.7.431.jar) 
	UCHIJAAAA	craftingtableiv{1.0} [CraftingTable-IV] (CraftingTableIV-1.4.113.jar) 
	UCHIJAAAA	craftingtweaks{7.1.9} [Crafting Tweaks] (CraftingTweaks_1.11.2_7.1.9.jar) 
	UCHIJAAAA	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized_Dungeon_Loot_1.11.2_v.1.0.1.jar) 
	UCHIJAAAA	disenchanter{1.6} [Disenchanter] (disenchanter_1.11.21.6.jar) 
	UCHIJAAAA	modutilslib{2.2.1} [ModUtilsLib] (modutilslib_2.2.1-mc1.11.jar) 
	UCHIJAAAA	dungeons2{1.0.0} [Dungeons2!] (dungeons2_1.0.0-mc1.11.jar) 
	UCHIJAAAA	easybreeding{4.1.0} [EasyBreeding] (easybreading_1.11.2_4.1.0.jar) 
	UCHIJAAAA	epicsiegemod{12.0.158} [Epic Siege Mod] (EpicSiegeMod_1.11.2_12.0.158.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix_0.7.1-law.jar) 
	UCHIJAAAA	giacomosfoundry{1.3.12} [Giacomo's Foundry] (GiacomosFoundry_1.11.2_1.3.12.jar) 
	UCHIJAAAA	grapplemod{1.11.2-v10} [Grappling hook mod] (grapplemod_1.11.2_v10.jar) 
	UCHIJAAAA	grimpack{4.0.1.20} [Grim Pack] (Grim_Pack_1.11.2_4.0.1.20.jar) 
	UCHIJAAAA	hammercore{1.9.3.9} [Hammer Core] (HammerCore_1.11.2-1.9.3.9.jar) 
	UCHIJAAAA	holoinventory{2.0.2.143} [HoloInventory] (HoloInventory_1.11.2_2.0.2.143.jar) 
	UCHIJAAAA	improvedmobs{1.1.6[1.11.2]} [Better Mob-AI] (ImprovedMobs_1.1.61.11.2.jar) 
	UCHIJAAAA	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs_1.11.2.jar) 
	UCHIJAAAA	inventorytweaks{1.63+dev.92.4367155} [Inventory Tweaks] (InventoryTweaks_1.11.2_1.63dev.92.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.24.809} [Iron Chest] (ironchest_1.11.2_7.0.24.809.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.5.0} [JourneyMap] (journeymap_1.11.2_5.5.0.jar) 
	UCHIJAAAA	llibrary{1.7.7} [LLibrary] (llibrary_1.7.7_1.11.2.jar) 
	UCHIJAAAA	lycanitesmobs{1.17.1.2 - MC 1.11.2} [Lycanites Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	arcticmobs{1.17.1.2 - MC 1.11.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	demonmobs{1.17.1.2 - MC 1.11.2} [Lycanites Demon Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	desertmobs{1.17.1.2 - MC 1.11.2} [Lycanites Desert Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	forestmobs{1.17.1.2 - MC 1.11.2} [Lycanites Forest Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	freshwatermobs{1.17.1.2 - MC 1.11.2} [Lycanites Freshwater Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	infernomobs{1.17.1.2 - MC 1.11.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	junglemobs{1.17.1.2 - MC 1.11.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	mountainmobs{1.17.1.2 - MC 1.11.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	plainsmobs{1.17.1.2 - MC 1.11.2} [Lycanites Plains Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	saltwatermobs{1.17.1.2 - MC 1.11.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	shadowmobs{1.17.1.2 - MC 1.11.2} [Lycanites Shadow Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	swampmobs{1.17.1.2 - MC 1.11.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete_1.17.1.2_1.11.2.jar) 
	UCHIJAAAA	malisiscore{1.11.2-5.2.5} [MalisisCore] (malisiscore_1.11.2-5.2.5.jar) 
	UCHIJAAAA	malisisswitches{1.11.2-4.1.0} [Malisis Switches] (malisisswitches_1.11.2-4.1.0.jar) 
	UCHIJAAAA	mcmultipart{2.0.1} [MCMultiPart] (MCMultiPart_Mod_1.11.2.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	natural_absorption{1.2.2} [Natural Absorption] (natural_absorption_1.11.2_1.2.3.jar) 
	UCHIJAAAA	playerstats2{14r} [Player Stats 2] (PlayerStats2_1.11.2-14r.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste_mc1.11.2_1.7.4.jar) 
	UCHIJAAAA	refinedstorage{1.4.16} [Refined Storage] (Refined-Storage-Mod_1.11.2.jar) 
	UCHIJAAAA	ruins{16.5} [Ruins Mod] (Ruins_1.11.2.jar) 
	UCHIJAAAA	sanlib{1.3.0} [SanAndreasPs Mod Library] (SanLib_1.11.2-1.3.0.jar) 
	UCHIJAAAA	sanplayermodel{1.0.2} [SanAndreasPs Player Model] (SanLib_1.11.2-1.3.0.jar) 
	UCHIJAAAA	shetiphiancore{3.4.7} [ShetiPhian-Core] (shetiphiancore_1.11.0_3.4.7.jar) 
	UCHIJAAAA	signedit{1.11.2-4} [SignEdit] (signedit_1.11.2_4.jar) 
	UCHIJAAAA	simplequarry{1.0.3} [Simple Quarry] (SimpleQuarry_1.11.2-1.0.3.jar) 
	UCHIJAAAA	sophisticatedwolves{3.9.1} [Sophisticated Wolves] (SophisticatedWolves_1.11.2_3.9.1.jar) 
	UCHIJAAAA	spartanshields{1.3} [Spartan Shields] (SpartanShields_1.11.2_1.3a.jar) 
	UCHIJAAAA	subcommonlib{1.2.0.1} [Subaraki's Common Library] (sublib_1.11.2.jar) 
	UCHIJAAAA	tammodized{0.9.2} [TamModized] (TamModized_1.11.2-0.9.2.jar) 
	UCHIJAAAA	telepads{1.11.2-1.0.2.1} [Telepads] (telepads_1.11.2-1.0.2.1.jar) 
	UCHIJAAAA	teleportingxp{1.1.1.1} [Teleporting XP] (teleportingxp_1.1.1.1.jar) 
	UCHIJAAAA	theoneprobe{1.4.19} [The One Probe] (theoneprobe_1.1x_1.4.19.jar) 
	UCHIJAAAA	toolbelt{1.7.1} [Tool Belt] (ToolBelt_1.11.2_1.7.1.jar) 
	UCHIJAAAA	torcharrowsmod{1.9.4-2} [TorchArrowsMod] (Torch-Arrows_1.11.2.jar) 
	UCHIJAAAA	toroquest{1.11.2-4.0} [ToroQuest] (toroquest_1.11.2_4.0.jar) 
	UCHIJAAAA	sapturretmod{4.0.0-beta.3} [Turret Mod Rebirth] (TurretMod_1.11.2-4.0.0-beta.3.jar) 
	UCHIJAAAA	upsizer{3.1} [Up-Sizer] (upsizer_mc1.11.2_3.1.jar) 
	UCHIJAAAA	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor_1.11.2_1.3.3.6.jar) 
	UCHIJAAAA	minersadvantage{1.2.15.193} [MinersAdvantage] (minersadvantage_1.11.2-1.2.15.194.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore_1.11.2-5.2.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
SpongeCoremod (spongeforge-1.11.2-2476-6.1.0-BETA-2792.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CoreMod (Aroma1997Core_1.11.2_1.2.0.0.jar)
  
ImprovedMobs/ASM (ImprovedMobs_1.1.61.11.2.jar)
  com.flemmli97.improvedmobs.asm.ASMTransformer
MalisisSwitchesPlugin (malisisswitches_1.11.2-4.1.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
ForgelinPlugin (Forgelin_1.4.2.jar)
  
llibrary (llibrary_1.7.7_1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (shetiphiancore_1.11.0_3.4.7.jar)
  shetiphian.core.asm.ClassTransformer
IvToolkit (IvToolkit_1.3.3._1.11.2jar.jar)
  
HammerCoreCore (HammerCore_1.11.2-1.9.3.9.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
NWRTweak (redstonepaste_mc1.11.2_1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (Bloodmoon_MC1.11.x_1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
MuonPlugin (muon_0.2.jar)
  gd.izno.mc.muon.MuonClassTransformer
Inventory Tweaks Coremod (InventoryTweaks_1.11.2_1.63dev.92.jar)
  invtweaks.forge.asm.ContainerTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 200; [EntityPlayerMP['xxx_LEOPARD_xxx'/1753, l='world', x=288,37, y=64,00, z=596,36]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```
</details>

**Comment by xxxLEOPARDxxx** [comment]
How soon to wait for updates for version 1.11.2?)

**Comment by DuelMonster** [comment]
I should get a fix out for your crash either tonight or tomorrow. 😊

**Comment by DuelMonster** [comment]
Released [1.2.15.195](https://minecraft.curseforge.com/projects/minersadvantage/files/2578720)

**Comment by xxxLEOPARDxxx** [comment]
Already again I wanted to ask when there will be an update and that's it!
And then I'm already tired of vanilla harvesting a ton of harvest ...

Checked, everything works! But there is one BUT)
Seeds are not wasted, which you select. It's as if they are setting themselves up as cheats.

**Comment by DuelMonster** [comment]
Sorry, I'm not quite sure what you are saying...

Do you mean that you are expecting the seeds in your inventory or those harvested along with your crops to be used up while harvesting?

If so, then I didn't design it that way; but I could add it to the enhancement list for a future release.

**Comment by xxxLEOPARDxxx** [comment]
Yes, you understood that)
It would be desirable that when digging up the crop and planting it again they are expended from the inventory.

**Comment by DuelMonster** [comment]
Ok, thanks. I'll add that to the list.
